### ISSUE TITLE
Unable to install on MacOS Ventura

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epidemics#119]
Please see attached file for the full error message. I've had this issue before, which I reported in #63. I got it fixed but it seems to have reappeared. I don't have this issue installing other packages that use cpp, so I'm not sure what the issue is here. This also seems to be related to #115. It seems the OS is the common denominator here.  
[epidemics_error.md](https://github.com/epiverse-trace/epidemics/files/12818502/epidemics_error.md)

**Comment by pratikunterwegs** [comment]
Thanks - could you try re-installing {finalsize} as well and check whether that works? It shares Rcpp-related dependencies with {epidemics} so would be good to check whether it is also affected. If it is not, that might help isolate the issue.

**Comment by jamesmbaazam** [comment]
I'm able to install/build `finalsize`.

I've fixed the issue through a series of try and errors.

I first ran `brew doctor` which showed that I had a few problematic files in my `/usr/local/include` directory, so I deleted that folder. 

Then I removed my current R installation using 
```bash
sudo rm -rf /Applications/R.app
sudo rm -rf /Library/Frameworks/R.framework
sudo rm /usr/bin/{R,Rscript}
```
and downgrading my R to 4.2.3.  

In the past, removing the `/usr/local/include` directory was enough to fix the issue, so I'm not sure if it's that or the R downgrade that fixed it.

**Comment by pratikunterwegs** [comment]
Thanks @jamesmbaazam for flagging this and trying various fixes. Downgrading R isn't a sustainable solution, so I'll take this up as a priority along with #63.

**Comment by pratikunterwegs** [comment]
Hi @jamesmbaazam thanks for the full error message. This issue seems to be the same as #115, and appears to be related to the use of `std::unary_function` and `std::binary_function` in {BH} (Boost Headers), which are [not compatible with Clang 15 provided with Xcode 15](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes).

A hacky looking fix is to 're-enable' these, as specified in the Xcode 15 release notes, but I'll check whether there are alternatives available before implementing this.

**Comment by pratikunterwegs** [comment]
This still doesn't explain why downgrading R might have fixed the issue.

**Comment by jamesmbaazam** [comment]
> This still doesn't explain why downgrading R might have fixed the issue.

I will upgrade my R to see if it reproduces the problem. I doubt that the downgrade fixed it but let me confirm.

**Comment by jamesmbaazam** [comment]
Yes, I have. I thought I left a comment here. Thanks.

**Comment by pratikunterwegs** [comment]
Fixed by #129.
